eShopSolution.AdminApp/Controllers/Components/PagerViewComponent.cs
using eShopSolution.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopSolution.AdminApp.Controllers.Components
{
	public class PagerViewComponent : ViewComponent
	{
		public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
		{
			return Task.FromResult((IViewComponentResult)View("Default", result));
		}
	}
}

eShopSolution.AdminApp/Controllers/ProductController.cs
using eShopSolution.ApiIntegration;
using eShopSolution.Utilities.Constans;
using eShopSolution.ViewModels.Catelog.Products;
using eShopSolution.ViewModels.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopSolution.AdminApp.Controllers
{
    [Authorize]
    public class ProductController : Controller
	{
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;
        private readonly ICategoryApiClient _categoryApiClient;
        public ProductController(
            IProductApiClient productApiClient,
            IConfiguration configuration,
            ICategoryApiClient categoryApiClient
        ){
            _configuration = configuration;
            _productApiClient = productApiClient;
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IActionResult> Index(string keyword, int? categoryId, int pageIndex = 1, int pageSize = 10)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var request = new GetManageProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                LanguageId = languageId,
                CategoryId = categoryId
            };
            var data = await _productApiClient.GetPagings(request);
            ViewBag.Keyword = keyword;

            var categories = await _categoryApiClient.GetAll(languageId);
            ViewBag.Categories = categories.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = categoryId.HasValue && categoryId.Value == x.Id
            });

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] ProductCreateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _productApiClient.CreateProduct(request);
            if (result)
            {
                TempData["result"] = "Thêm mới sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm sản phẩm thất bại");
            return View(request);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var product = await _productApiClient.GetById(id, languageId);
            var editVm = new ProductUpdateRequest()
            { 
                Id = product.Id,
                Description = product.Description,
                Details = product.Details,
                Name = product.Name,
                SeoAlias = product.SeoAlias,
                SeoDescription = product.SeoDescription,
                SeoTitle = product.SeoTitle
            };
            return View(editVm);
        }
        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit([FromForm] ProductUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _productApiClient.UpdateProduct(request);
            if (result)
            {
                TempData["result"] = "Cập nhật sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cập nhật sản phẩm thất bại");
            return View(request);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(new ProductDeleteRequest()
            {
                Id = id
            });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ProductDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _productApiClient.DeleteProduct(request.Id);
            if (result)
            {
                TempData["result"] = "Xóa thành công";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Xóa không thành công!");
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> CategoryAssign(int id)
        {
            var roleAssignRequest = await GetCategoryAssignRequest(id);
            return View(roleAssignRequest);
        }

        [HttpPost]
        public async Task<IActionResult> CategoryAssign(CategoryAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _productApiClient.CategoryAssign(request.Id, request);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            var roleAssignRequest = await GetCategoryAssignRequest(request.Id);

            return View(roleAssignRequest);
        }
        private async Task<CategoryAssignRequest> GetCategoryAssignRequest(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var productObj = await _productApiClient.GetById(id, languageId);
            var categories = await _categoryApiClient.GetAll(languageId);
            var categoryAssignRequest = new CategoryAssignRequest();
            foreach (var role in categories)
            {
                categoryAssignRequest.Categories.Add(new SelectItem()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = productObj.Categories.Contains(role.Name)
                });
            }
            return categoryAssignRequest;
        }
    }
}

eShopSolution.AdminApp/Views/Product/CategoryAssign.cshtml
@model eShopSolution.ViewModels.Catelog.Products.CategoryAssignRequest

@{
    ViewData["Title"] = "Gán danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-content">

    <div class="main-content-inner">

        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="/">Tổng quan</a>
                </li>
                <li class="active">Gắn danh mục</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>
        <form asp-action="CategoryAssign">
            <div class="page-content">
                <div class="page-header clearfix">
                    <div class="form-group float_right">
                        <button type="submit" value="Create" class="btn btn-sm btn-info">Cập nhật</button>
                    </div>
                </div><!-- /.page-header -->
                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        @for (var i = 0; i < Model.Categories.Count; i++)
                        {
                            <div class="form-group">
                                <label>
                                    @Model.Categories[i].Name
                                    <input type="checkbox" asp-for="Categories[i].Selected" />
                                    <input type="hidden" asp-for="Categories[i].Id" />
                                    <input type="hidden" asp-for="Categories[i].Name" />
                                </label>
                            </div>
                        }
                        <div class="form-group">
                            <input type="submit" value="Lưu lại" class="btn btn-primary" />
                        </div>
                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </form>
    </div>
</div><!-- /.main-content -->

eShopSolution.AdminApp/Views/Product/Create.cshtml
@model eShopSolution.ViewModels.Catelog.Products.ProductCreateRequest

@{
    ViewData["Title"] = "Thêm sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
        <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
        <script>
            ClassicEditor
                .create(document.querySelector('#Details'), {
                    toolbar: [ 'heading', '|', 'bold', 'italic', 'link','color','gradient','html','source' ]
                })
                .then(editor => {
                    window.editor = editor;
                })
                .catch(err => {
                    console.error(err.stack);
                });
        </script>
    }
<div class="main-content">

    <div class="main-content-inner">

        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="/">Tổng quan</a>
                </li>
                <li class="active">Thêm sản phẩm</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div class="page-content">
                <div class="page-header clearfix">
                    <div class="form-group float_right">
                        <button type="submit" value="Create" class="btn btn-sm btn-info">Cập nhật</button>
                    </div>
                </div><!-- /.page-header -->
                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label">Tên sản phẩm</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ThumbnailImage" class="control-label">Ảnh đại diện</label>
                            <input asp-for="ThumbnailImage" type="file" class="form-control" />
                            <span asp-validation-for="ThumbnailImage" class="text-danger"></span>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label asp-for="Price" class="control-label">Giá bán</label>
                                    <input asp-for="Price" class="form-control" />
                                    <span asp-validation-for="Price" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label asp-for="OriginalPrice" class="control-label">Giá gốc</label>
                                    <input asp-for="OriginalPrice" class="form-control" />
                                    <span asp-validation-for="OriginalPrice" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label asp-for="Stock" class="control-label">Số lượng còn lại</label>
                                    <input asp-for="Stock" class="form-control" />
                                    <span asp-validation-for="Stock" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label asp-for="ViewCount" class="control-label"></label>
                                    <input asp-for="ViewCount" class="form-control" />
                                    <span asp-validation-for="ViewCount" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label">Mô tả</label>
                            <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Details" class="control-label">Chi tiết</label>
                            <textarea asp-for="Details" id="Details" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Details" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoDescription" class="control-label">Mô tả seo</label>
                            <input asp-for="SeoDescription" class="form-control" />
                            <span asp-validation-for="SeoDescription" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoTitle" class="control-label">Title Seo</label>
                            <input asp-for="SeoTitle" class="form-control" />
                            <span asp-validation-for="SeoTitle" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoAlias" class="control-label">Đường dẫn seo</label>
                            <input asp-for="SeoAlias" class="form-control" />
                            <span asp-validation-for="SeoAlias" class="text-danger"></span>
                        </div>
                        <div>
                            <a asp-action="Index">Back to List</a>
                        </div>
                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </form>
    </div>
</div><!-- /.main-content -->

eShopSolution.AdminApp/Views/Product/Delete.cshtml
@model eShopSolution.ViewModels.Catelog.Products.ProductDeleteRequest

@{
    ViewData["Title"] = "Xóa sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="main-content">

    <div class="main-content-inner">

        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="/">Tổng quan</a>
                </li>
                <li class="active">Xóa sản phẩm</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header clearfix">

            </div><!-- /.page-header -->
            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <div>
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Id)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Id)
                            </dd>
                        </dl>

                        <form asp-action="Delete">
                            <input asp-for="Id" type="hidden" />
                            <input type="submit" value="Xóa" class="btn btn-sm btn-danger" />
                        </form>
                    </div>
                    <!-- PAGE CONTENT ENDS -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->

eShopSolution.AdminApp/Views/Product/Edit.cshtml
@model eShopSolution.ViewModels.Catelog.Products.ProductUpdateRequest

@{
    ViewData["Title"] = "Cập nhật sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
        <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
        <script>
            ClassicEditor
                .create(document.querySelector('#Details'), {
                    toolbar: [ 'heading', '|', 'bold', 'italic', 'link','color','gradient','html','source' ]
                })
                .then(editor => {
                    window.editor = editor;
                })
                .catch(err => {
                    console.error(err.stack);
                });
        </script>
    }
<div class="main-content">

    <div class="main-content-inner">

        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="/">Tổng quan</a>
                </li>
                <li class="active">Cập nhật sản phẩm</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div class="page-content">
                <div class="page-header clearfix">
                    <div class="form-group float_right">
                        <button type="submit" value="Edit" class="btn btn-sm btn-info">Cập nhật</button>
                    </div>
                </div><!-- /.page-header --> 
                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="Name" class="control-label">Tên sản phẩm</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ThumbnailImage" class="control-label">Ảnh đại diện</label>
                            <input asp-for="ThumbnailImage" type="file" class="form-control" />
                            <span asp-validation-for="ThumbnailImage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label">Mô tả</label>
                            <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Details" class="control-label">Chi tiết</label>
                            <textarea asp-for="Details" id="Details" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Details" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoDescription" class="control-label">Mô tả seo</label>
                            <input asp-for="SeoDescription" class="form-control" />
                            <span asp-validation-for="SeoDescription" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoTitle" class="control-label">Title Seo</label>
                            <input asp-for="SeoTitle" class="form-control" />
                            <span asp-validation-for="SeoTitle" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoAlias" class="control-label">Đường dẫn seo</label>
                            <input asp-for="SeoAlias" class="form-control" />
                            <span asp-validation-for="SeoAlias" class="text-danger"></span>
                        </div>
                        <div>
                            <a asp-action="Index">Back to List</a>
                        </div>
                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </form>
    </div>
</div><!-- /.main-content -->

eShopSolution.AdminApp/Views/Product/Index.cshtml
@using eShopSolution.ViewModels.Common;
@model PagedResult<eShopSolution.ViewModels.Catelog.Products.ProductVm>

@{
    ViewData["Title"] = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
}
<div class="main-content">

    <div class="main-content-inner">

        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="/">Tổng quan</a>
                </li>
                <li class="active">Danh sách sản phẩm</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header clearfix">
                <a href="/product/create" class="btn btn-sm btn-info" style="float: right">Thêm mới</a>
            </div><!-- /.page-header -->
            <div class="content-search clearfix">
                <div class="row">
                    <form asp-action="Index" asp-controller="Product" method="get">
                        <div class="col-sm-2">
                            <div class="form-group">
                                <input type="text" class="form-control" value="@ViewBag.Keyword" name="keyword" placeholder="Tên sản phẩm" style="font-size: 12px;" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <select name="categoryId" onchange="this.form.submit()" asp-items="@ViewBag.Categories" class="form-control">
                                <option>--Chọn danh mục--</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <button class="btn btn-sm btn-info">Tìm kiếm</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    @if (ViewBag.SuccessMsg != null)
                    {
                        <div id="msgAlert" class="alert alert-success" role="alert">
                            @ViewBag.SuccessMsg
                        </div>
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Mã SP
                                </th>
                                <th>
                                    Tên
                                </th>
                                <th>
                                    Giá nhập
                                </th>
                                <th>
                                    Giá bán
                                </th>
                                <th>
                                    Số lượng tồn
                                </th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Items)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.OriginalPrice)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Price)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Stock)
                                    </td>

                                    <td>
                                        @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Xem", "Details", new { id = item.Id }) |
                                        @Html.ActionLink("Xóa", "Delete", new { id = item.Id }) |
                                        @Html.ActionLink("Gán danh mục", "CategoryAssign", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @await Component.InvokeAsync("Pager", Model)
                    <!-- PAGE CONTENT ENDS -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->